services:
  AnimeTagger:
    image: animetagger 
    build:
      context: ./AnimeTagger/ 
    ports:
      - "50051:50051"
    env_file:
      - path: "./.env"
  imagemanager:
    image: imagemanager
    build:
      context: ./ImageManager/
    profiles:
      - "backend"
    depends_on:
      - database
    env_file:
      - path: "./.env"
  database:
    image: 'postgres:latest'
    networks:
      - network
    env_file:
      - path: "./.env"
        required: true
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    profiles:
      - "database"

networks:
  network:
    driver: bridge
volumes:
  db-data:
