services:
  AnimeTagger:
    image: registry.orbitalperiod.net/animetagger:latest
    build:
      context: ./AnimeTagger/
    env_file:
      - "./.env"
      - "./.docker.env"
    networks: ["imagemanager_network"]

  imagemanager:
    image: registry.orbitalperiod.net/imagemanager:latest
    build:
      context: ./ImageManager/ 
    ports:
      - "8173:8080"
    env_file:
      - "./.env"
      - "./.docker.env"
      - path: "./.secrets.env"
        required: false
    volumes:
      - images:/Images
    depends_on:
      database:
        condition: service_healthy
    networks: ["imagemanager_network", "network"]

  database:
    image: postgres:latest
    env_file:
      - "./.env"
      - "./.docker.env"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks: ["imagemanager_network"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgresql"]
      interval: 5s
      timeout: 2s
      retries: 10

  frontend:
    image: registry.orbitalperiod.net/frontend:latest
    build:
      context: ./Frontend/
    env_file:
      - "./.env"
      - "./.docker.env"
    ports:
      - "8081:80"
    networks: ["imagemanager_network"]

networks:
  imagemanager_network:
    driver: bridge
  network:
    external: true

volumes:
  db-data:
  images:
