services:
  AnimeTagger:
    networks: ["imagemanager_network"]
    ports:
      - "50051:50051"
    profiles: ["Tagger"]

  imagemanager:
    networks: ["imagemanager_network"]
    ports:
      - "8080:8080"
    profiles: ["Backend"]

  database:
    networks: ["imagemanager_network"]
    ports:
      - "5432:5432"

  frontend:
    networks: ["imagemanager_network"]
    profiles: ["Frontend"]
